### ISSUE TITLE
Send HD Image from Camera

### ISSUE THREAD

**Issue by rahulk64** [primitive-apps/Primitive-Android#5]
Right now, we are running into limitations where we can only send scaled-down images from the camera across to the Preview Activity, which decreases the quality of the overall image. We need to find a way to send over the Uri/Path instead of the image itself.

**Comment by jordanbuchman** [comment]
I don't think this matters. Primitive actually recommends reducing image
resolution before processing.

**Comment by rahulk64** [comment]
Well the problem is that there are two activities (the preview activity and the primitive menu/options activity that the user will see the blocky image in, so it would be preferable to reduce image quality only right before we run the Primitive library on the image.
